README.md
package-lock.json
package.json
src/__tests__/encrypt.e2e.test.ts
src/encrypt.ts
src/index.ts

TODO:
- update openattestation.com
- update README

feat: add encrypt command

---

.releaserc

Fix binary files that do not return version number properly

fix: bin file version

---

src/commands/wrap.ts
src/implementations/wrap/diskUtils.ts
src/implementations/wrap/wrap.ts

https://github.com/Open-Attestation/open-attestation-cli/issues/29

 feat: allow add dns txt proof when wrap

---

src/commands/wrap.ts
src/implementations/wrap/wrap.ts

https://github.com/Open-Attestation/open-attestation-cli/issues/28

feat: add doc store

---

src/commands/wrap.ts
src/implementations/wrap/wrap.ts

for https://github.com/Open-Attestation/open-attestation-cli/issues/30

feat: add template url

---

README.md
src/commands/token-registry.ts
src/commands/token-registry/issue.ts
src/commands/token-registry/mint.ts
src/commands/token-registry/token-registry-command.type.ts
src/implementations/token-registry/issue.test.ts
src/implementations/token-registry/issue.ts

feat: issue (or mint) to token registry

---

src/commands/deploy/deploy.types.ts
src/commands/deploy/document-store.ts
src/commands/deploy/title-escrow-creator.ts
src/commands/deploy/title-escrow.ts
src/commands/deploy/token-registry.ts
src/commands/document-store/document-store-command.type.ts
src/commands/document-store/issue.ts
src/commands/document-store/revoke.ts
src/commands/shared.ts
src/commands/token-registry/issue.ts
src/commands/token-registry/token-registry-command.type.ts
src/implementations/deploy/document-store/document-store.test.ts
src/implementations/deploy/document-store/document-store.ts
src/implementations/deploy/title-escrow-creator/title-escrow-creator.test.ts
src/implementations/deploy/title-escrow-creator/title-escrow-creator.ts
src/implementations/deploy/title-escrow/title-escrow.test.ts
src/implementations/deploy/title-escrow/title-escrow.ts
src/implementations/deploy/token-registry/token-registry.test.ts
src/implementations/deploy/token-registry/token-registry.ts
src/implementations/document-store/issue.test.ts
src/implementations/document-store/issue.ts
src/implementations/document-store/revoke.test.ts
src/implementations/document-store/revoke.ts
src/implementations/token-registry/issue.test.ts
src/implementations/token-registry/issue.ts

@yehjxraymond @rjchow 
- Added gas-price-scale which accept a number with will be applied to the gas price

feat: add option to adjust gas price

---

package-lock.json
package.json
src/__tests__/encrypt.e2e.test.ts
src/__tests__/sign.e2e.test.ts
src/__tests__/wrap.e2e.test.ts
src/implementations/sign/sign.ts

chore: fix flaky test

---

src/commands/deploy/deploy.types.ts
src/commands/deploy/title-escrow.ts
src/implementations/deploy/title-escrow/title-escrow.ts

```
mainnet: "0x907A4D491A09D59Bcb5dC38eeb9d121ac47237F1",
ropsten: "0xB0dE5E22bAc12820b6dbF6f63287B1ec44026c83",
rinkeby: "0xa51B8dAC076d5aC80507041146AC769542aAe195",
```

feat: default title escrow creator contracts

---

src/__tests__/verify.e2e.test.ts
src/__tests__/wrap.e2e.test.ts
src/commands/verify.ts

it was not working anymore because we merged the revoked verifier into the document store verifier.

fix: verify function

---

README.md
src/__tests__/wrap.e2e.test.ts
src/__tests__/wrap.test.ts
src/commands/wrap.ts
src/implementations/deploy/document-store/document-store.test.ts
src/implementations/deploy/title-escrow-creator/title-escrow-creator.test.ts
src/implementations/deploy/title-escrow/title-escrow.test.ts
src/implementations/deploy/token-registry/token-registry.test.ts
src/implementations/document-store/issue.test.ts
src/implementations/document-store/revoke.test.ts
src/implementations/wallet/__tests__/create.test.ts
src/implementations/wallet/__tests__/encrypt.test.ts
src/implementations/wrap/wrap.ts

also adding higher timeout for some test due to ethers throttling

feat: wrap document individually with --batched flag

---

src/commands/dns/txt-record/create.ts
src/commands/dns/txt-record/dns-command.type.ts

feat: configurable dns sandbox target

---

src/implementations/wallet/create.ts

- updated the faucet url to use the one from open attestation 
faucet.openattestation.com

fix: replace faucet URL to use openattestation

---

README.md

- `This command process all documents in the input directory and issue all of them in a single batch` => the issue part sounds abit wrong in this sentence

chore: text edit

---

src/commands/deploy/title-escrow.ts

To fix issue: https://github.com/Open-Attestation/open-attestation-cli/issues/133

fix: added types for arguments

---

src/commands/document-store/document-store-command.type.ts
src/commands/document-store/transfer-ownership.ts
src/implementations/document-store/transfer-ownership.test.ts
src/implementations/document-store/transfer-ownership.ts

Story - https://www.pivotaltracker.com/n/projects/2464296/stories/178684134

add transfer document-store transferOwnership command

---

src/commands/config/__tests__/create.test.ts
src/commands/config/__tests__/expected-config-file-using-insert-file-option.json
src/commands/config/__tests__/expected-config-file-using-type-option.json
src/commands/config/__tests__/input-config-file.json
src/commands/config/create.ts
src/commands/config/templates/tradetrust.json

- update wallet to cater to wallet type

fix: update wallet type

---

src/commands/config/__tests__/expected-config-file-using-type-option.json
src/commands/config/create.ts
src/commands/config/templates/tradetrust.json

remove useless and sensitive data from template file
- remove useless data from template file
- remove sensitive data from template file

fix: remove useless and sensitive data

---

package-lock.json
package.json

Upgraded OA to latest version for testing and tutorial of did revocation

chore: upgrade oa to latest

---

src/implementations/config/create.ts
src/implementations/config/helpers.ts
src/implementations/config/types.ts

refactor: get config

---

src/__tests__/error-handling.test.ts
src/commands/deploy/document-store.ts
src/commands/deploy/title-escrow-creator.ts
src/commands/deploy/title-escrow.ts
src/commands/deploy/token-registry.ts
src/commands/dns/txt-record/create.ts
src/commands/dns/txt-record/get.ts
src/commands/document-store/issue.ts
src/commands/document-store/revoke.ts
src/commands/document-store/transfer-ownership.ts
src/commands/title-escrow/accept-surrendered.ts
src/commands/title-escrow/change-holder.ts
src/commands/title-escrow/endorse-change-of-owner.ts
src/commands/title-escrow/endorse-transfer-of-owner.ts
src/commands/title-escrow/nominate-change-of-owner.ts
src/commands/title-escrow/reject-surrendered.ts
src/commands/title-escrow/surrender-document.ts
src/commands/token-registry/issue.ts
src/commands/transaction/cancel.ts
src/commands/wallet/create.ts
src/commands/wallet/decrypt.ts
src/commands/wallet/encrypt.ts
src/implementations/transaction/transaction.ts
src/utils.ts

fix: only TypeErrors printed

---

src/implementations/utils/dryRun.ts

fix: dry run underflow error

---

package-lock.json
package.json
src/implementations/config/create.ts
src/implementations/config/helpers.ts
src/implementations/config/types.ts

- Added support for v3 config file. 
https://www.pivotaltracker.com/n/projects/2424361/stories/180703033

feat: added support for v3 config file

---

package-lock.json
package.json

Fix: document store deps

---

README.md
src/commands/networks.ts
src/commands/shared.ts
src/implementations/config/helpers.ts
src/implementations/config/types.ts
src/implementations/document-store/issue.ts
src/implementations/document-store/revoke.ts
src/implementations/document-store/transfer-ownership.ts
src/implementations/title-escrow/acceptSurrendered.ts
src/implementations/title-escrow/endorseChangeOfOwner.ts
src/implementations/title-escrow/endorseTransferOfOwner.ts
src/implementations/title-escrow/nominateChangeOfOwner.ts
src/implementations/title-escrow/rejectSurrendered.ts
src/implementations/title-escrow/surrenderDocument.ts
src/implementations/token-registry/issue.ts
src/implementations/utils/wallet.ts
src/utils.ts

enable goerli option as per discuss [here](https://github.com/Open-Attestation/open-attestation/discussions/238).

feat: add support for goerli and polygon

---

src/commands/networks.ts
src/implementations/config/types.ts

A minor refactor to the changes made in #210 for the network providers before adding sepolia.
- fix localhost provider
- remove redundant chain id
- minor clean up
- #210

refactor: network provider

---

README.md

- typo in documentation command

docs: verify document

---

package-lock.json
package.json
src/commands/networks.ts
src/commands/verify.ts

Add support for sepolia testnet.
- Add sepolia network information to config file
- https://www.pivotaltracker.com/story/show/183149344

feat: add support for sepolia

---

package-lock.json
src/implementations/config/create.ts

update create temporary dns for goerli network
- update network id to 5

feat: update network id to goerli

---

README.md
src/commands/networks.ts
src/commands/wallet/create.ts
src/implementations/config/__tests__/error-config-file.json
src/implementations/config/__tests__/expected-config-file-output.json
src/implementations/config/__tests__/input-config-file.json
src/implementations/deploy/title-escrow/title-escrow.ts
src/implementations/wallet/create.ts

Deprecate Ropsten and Rinkeby testnets
_In preparation for 27 Oct_
- deprecate Ropsten and Rinkeby
- Replace them with Goerli as default
https://www.pivotaltracker.com/n/projects/2424361/stories/183540476

feat: deprecate ropsten and rinkeby

---

.gitignore
README.md
src/commands/config/config.type.ts
src/commands/config/create.ts
src/commands/deploy/deploy.types.ts
src/commands/networks.ts
src/commands/shared.ts
src/implementations/config/__tests__/config-reference-v3.json
src/implementations/config/__tests__/create.test.ts
src/implementations/config/__tests__/expected-config-file-output-v3.json
src/implementations/config/__tests__/expected-config-file-output.json
src/implementations/config/__tests__/helpers.test.ts
src/implementations/config/__tests__/input-config-file.json
src/implementations/config/create.ts
src/implementations/config/helpers.ts
src/implementations/config/types.ts
src/implementations/deploy/document-store/document-store.ts
src/implementations/deploy/token-registry/token-registry.ts
src/implementations/utils/wallet.ts

Update Config create command to create config file for polygon mumbai testnet.
- Updated config create command to handle different networks
- Update and added more test cases
https://www.pivotaltracker.com/n/projects/2424361/stories/181365136
https://www.pivotaltracker.com/n/projects/2424361/stories/181365137

feat: update create config command for different networks

---

package-lock.json
package.json
src/implementations/config/helpers.ts

As per moved to [here](https://github.com/TradeTrust/tradetrust-config/blob/9bf4b9a78434e54532bde24dd47631dbd2259b36/src/shared/updateForm.ts#L25).
- no functional change, use from `@govtechsg/tradetrust-config` instead

fix: update form

---

package.json

Issue with CI when releasing. Error mentions about `pkg`.
- Attempt to use `npx` for `pkg`
- https://www.pivotaltracker.com/story/show/184994559

fix: issue with pkg in ci

---

.releaserc

Miss out something in the previous PR in #265 
- Update releaserc
- https://www.pivotaltracker.com/story/show/184994559

fix: release issue

---

.releaserc

fml please work.
- https://www.pivotaltracker.com/story/show/184994559

fix: release issue again

---

package-lock.json
package.json

- dist file wasn't include after some refactoring
- fix on dependancy end https://github.com/TradeTrust/tradetrust-config/pull/62

fix: tt config

---

README.md
src/commands/config/config.type.ts
src/commands/config/create.ts
src/commands/networks.ts

Remove Goerli network from the CLI
- Remove Goerli network from the CLI
- https://www.pivotaltracker.com/story/show/186138607

feat: remove goerli
