- README.md
- src/__tests__/wrap.e2e.test.ts
- src/__tests__/wrap.test.ts
- src/commands/wrap.ts
- src/implementations/wrap/diskUtils.ts
- src/implementations/wrap/wrap.ts
https://github.com/Open-Attestation/open-attestation-cli/issues/26
What i tried:
Implementing directory or file identification before the function call instead of within the function as in https://github.com/Open-Attestation/open-attestation-cli/pull/33/commits/92d89f58c1951c7c4163751c1f39464a3f4f2223
This causes the test to work but i am unable to get https://github.com/Open-Attestation/open-attestation-cli/issues/26 resolved as i could previously.
Right now:
I have reverted back the  directory or file identification within the function call.
https://github.com/Open-Attestation/open-attestation-cli/issues/26 has been resolved.
However i am unable to get wrap.test.ts to pass all tests.
Error:     TypeError: (0 , _diskUtils.isDir) is not a function
> feat: handle file as input when calling wrap

- src/__tests__/wrap.e2e.test.ts
- Wrong variable used for tests for file as input: inputDirectoryName => inputDirectory (inputDirectoryTwo)
- Tests fail sometime => because the test for file as input and the test for directory as input uses the same temporary folder tmp_in, hence when the tests run out of order, the two tests interleave causing race condition between the rimraf operations. This results in the folders not being cleared properly, causing futher tests to face errors such as 'folder already exists'.
=> separate tmp_in_two used
> test: fix wrap e2e test

- package-lock.json
- src/commands/shared.ts
- src/implementations/deploy/document-store/document-store.test.ts
- src/implementations/deploy/document-store/document-store.ts
- src/implementations/deploy/title-escrow-creator/title-escrow-creator.test.ts
- src/implementations/deploy/title-escrow-creator/title-escrow-creator.ts
- src/implementations/deploy/title-escrow/title-escrow.test.ts
- src/implementations/deploy/title-escrow/title-escrow.ts
- src/implementations/deploy/token-registry/token-registry.test.ts
- src/implementations/deploy/token-registry/token-registry.ts
- src/implementations/document-store/issue.test.ts
- src/implementations/document-store/issue.ts
- src/implementations/document-store/revoke.test.ts
- src/implementations/document-store/revoke.ts
- src/implementations/token-registry/issue.test.ts
- src/implementations/token-registry/issue.ts
- src/implementations/utils/dryRun.ts
- src/utils.ts
Run transaction using dry-run to get information about the cost. Use `--dry-run` on any command needing a transaction.
In order to work, the transaction must be valid on the network you selected (otherwise it will fail) and the result is displayed depending on `mainnet` network price, whatever network you run the transaction on. (gas needed is not dependent of the network)
Currently deploying a token registry does not work:
- https://community.infura.io/t/eth-estimategas-always-fail-on-a-specific-contract/1801
- https://community.cloudflare.com/t/cloudflare-ethereum-eth-estimategas/192306
> feat: dry run

- package-lock.json
- package.json
- src/implementations/deploy/document-store/document-store.test.ts
- src/implementations/deploy/title-escrow-creator/title-escrow-creator.test.ts
- src/implementations/deploy/title-escrow/title-escrow.test.ts
- src/implementations/deploy/token-registry/token-registry.test.ts
This PR upgrade token registry to v2.3.0 to ensure deployed token registry can burn tokens
> feat: upgrade to token-registry@2.3.0

- src/implementations/utils/disk.ts
Issues : Unable to detect .oa unwrapped files
Problem: Failed validation check due to .oa not in valid ext
Solution: Added .oa to valid ext
> chore: added oa ext

- package-lock.json
- package.json
@govtechsg/token-registry: 2.5.1
This new version includes the updated interfaceID that is registered in the TradeTrustERC721.sol smart contract.
> fix: update token registry package version

- src/__tests__/fixture/2.0/custom-schema-with-nested-ref.json
- src/__tests__/fixture/2.0/custom-schema.json
- src/__tests__/fixture/2.0/schema.json
- src/__tests__/fixture/2.0/valid-custom-schema-document.json
- src/__tests__/fixture/2.0/valid-custom-schema-with-nested-ref-document.json
- src/__tests__/wrap.v2.e2e.test.ts
- src/implementations/wrap/wrap.ts
- add in async functionality for loading schema for ajv validator
- add in e2e tests for wrapping for various different schemas
context: https://github.com/Open-Attestation/open-attestation-cli/issues/122
this pr does the following:
- converts the existing ajv.compile into an async one
- adds additional v2 schemas to cover the cases whereby a custom schema has a nested ref.
please tell me if im duplicating code for e2e testing here, i took a look around, doesnt seem to have an e2e wrap test for v2 documents.
also is this a good decision in the first place to convert the sync compile into an async one?
i was thinking of looking up a definitive key for a nested ref in a custom schema to state that its a schema with a nested ref, then only do the async compile but i feel like it might be …
> fix: error thrown by ajv when encountering a nested ref

- README.md
- src/commands/transaction.ts
- src/commands/transaction/cancel.ts
- src/commands/transaction/transaction-command.type.ts
- src/implementations/transaction/index.ts
- src/implementations/transaction/transaction.test.ts
- src/implementations/transaction/transaction.ts
Added CLI command to cancel a pending transaction.
You can test in an actual ethereum environment by creating a pending transaction using the command below. 
open-attestation document-store issue --address <document-store> --hash <merkleroot> —network ropsten --gps 0 --encrypted-wallet-path ../wallet.json
The command will create a transaction to issue the hash into document-store and set the gas price to be 0 forcing it to constant pending. From the etherscan u can get the pending transaction nonce to test the transaction cancel command
> Feat : add cancel transaction command

- src/implementations/utils/dryRun.ts
- non-integer values causes underflow in ethers bignumber type
- see https://github.com/ethers-io/ethers.js/issues/488
> fix: round off gas price in gwei so that it is an integer

- src/commands/shared.ts
- src/implementations/utils/wallet.ts
Make accessKeyId optional and add use-env argument to allow for the kmsSigner to reference env vars directly.
> chore: allow kmsSigner to use env vars

- .circleci/config.yml
Update ci context name to the new name `deployment`.
> fix: update ci context name

- README.md
- performance-tests/wrap-performance-test.ts
- src/__tests__/fixture/2.0/unwrapped-example.1.json
- src/__tests__/fixture/2.0/unwrapped-example.2.json
- src/__tests__/fixture/2.0/wrapped-example.1.json
- src/__tests__/fixture/2.0/wrapped-example.2.json
- src/__tests__/unwrap.test.ts
- src/__tests__/wrap.test.ts
- src/commands/unwrap.ts
- src/commands/wrap.ts
- src/implementations/unwrap/index.ts
- src/implementations/unwrap/unwrap.ts
- src/implementations/utils/disk.ts
- src/implementations/wrap/wrap.ts
**Context**
To support unwrapping of a single wrapped document in the OA CLI
**What does this PR do?**
Supports the command below to take in a single wrapped document and unwrap it to a specified folder output. 
Command - `npm run dev -- unwrap <wrapped-document-file> --output-file <output-document-file>`
> feat: add unwrapping feature to OA CLI

- src/__tests__/verify.v2.e2e.test.ts
- src/__tests__/verify.v3.e2e.test.ts
- src/implementations/config/helpers.ts
- src/implementations/deploy/document-store/document-store.test.ts
- src/implementations/deploy/title-escrow-creator/title-escrow-creator.test.ts
- src/implementations/deploy/title-escrow/title-escrow.test.ts
- src/implementations/deploy/token-registry/token-registry.test.ts
- src/implementations/document-store/issue.test.ts
- src/implementations/document-store/revoke.test.ts
- src/implementations/document-store/transfer-ownership.test.ts
- src/implementations/title-escrow/acceptSurrendered.test.ts
- src/implementations/title-escrow/changeHolder.test.ts
- src/implementations/title-escrow/endorseChangeOfOwner.test.ts
- src/implementations/title-escrow/endorseTransferOfOwner.test.ts
- src/implementations/title-escrow/nominateChangeOfOwner.test.ts
- src/implementations/title-escrow/rejectSurrendered.test.ts
- src/implementations/title-escrow/surrenderDocument.test.ts
- src/implementations/token-registry/issue.test.ts
- src/implementations/transaction/transaction.test.ts
- src/implementations/utils/__tests__/wallet.test.ts
The tests are all breaking because they were connecting to Ropsten. This PR updates the network in the tests from Ropsten to Goerli.
- Update all tests to use Goerli instead of Ropsten
- https://www.pivotaltracker.com/story/show/183520197
> test: update networks used from ropsten to goerli

- src/__tests__/verify.v2.e2e.test.ts
- src/__tests__/verify.v3.e2e.test.ts
- src/implementations/config/helpers.ts
- src/implementations/deploy/document-store/document-store.test.ts
- src/implementations/deploy/title-escrow-creator/title-escrow-creator.test.ts
- src/implementations/deploy/title-escrow/title-escrow.test.ts
- src/implementations/deploy/title-escrow/title-escrow.ts
- src/implementations/deploy/token-registry/token-registry.test.ts
- src/implementations/document-store/issue.test.ts
- src/implementations/document-store/revoke.test.ts
- src/implementations/document-store/transfer-ownership.test.ts
- src/implementations/title-escrow/acceptSurrendered.test.ts
- src/implementations/title-escrow/changeHolder.test.ts
- src/implementations/title-escrow/endorseChangeOfOwner.test.ts
- src/implementations/title-escrow/endorseTransferOfOwner.test.ts
- src/implementations/title-escrow/nominateChangeOfOwner.test.ts
- src/implementations/title-escrow/rejectSurrendered.test.ts
- src/implementations/title-escrow/surrenderDocument.test.ts
- src/implementations/token-registry/issue.test.ts
- src/implementations/transaction/transaction.test.ts
- src/implementations/utils/__tests__/wallet.test.ts
Add Title Escrow Creator for Goerli network. Note that this is for the old v2 version of the token registry.
- Add Title Escrow Creator for Goerli
- https://www.pivotaltracker.com/story/show/183520213
> feat: add title escrow creator for goerli

- src/implementations/deploy/title-escrow/title-escrow.ts
Add missing title escrow creator (v2.x) for Sepolia and Polygon Mumbai.
- Add title escrow creator address for Sepolia 
- Add title escrow creator address for Polygon Mumbai.
- https://github.com/Open-Attestation/open-attestation-cli/issues/231
- https://www.pivotaltracker.com/story/show/183648956
> fix: add sepolia and mumbai escrow creator

- package-lock.json
- package.json
- src/implementations/deploy/document-store/document-store.test.ts
- src/implementations/deploy/document-store/document-store.ts
Bumps the document store to use v2.4.0 in CLI.
- Bumps document store to v2.4.0
- Set deployer as the default owner
- https://github.com/Open-Attestation/document-store/pull/122
> fix: bump doc store

- README.md
- src/commands/deploy/deploy.types.ts
- src/commands/deploy/document-store.ts
- src/implementations/deploy/document-store/document-store.test.ts
- src/implementations/deploy/document-store/document-store.ts
Add an option for document store deployment to allow a deployer to specify a different owner than herself.
- Add an optional `--owner` option to document-store deploy command
- Update tests
- Update readme doc
- https://www.pivotaltracker.com/story/show/183880095
-  #237 
- https://github.com/Open-Attestation/document-store/pull/122
> feat: document store owner option

- .gitignore
- README.md
- package-lock.json
- package.json
- src/commands/networks.ts
- src/implementations/config/__tests__/create.test.ts
- src/implementations/config/__tests__/expected-config-file-output-v2.json
- src/implementations/config/__tests__/expected-config-file-output-v3.json
- src/implementations/config/__tests__/helpers.test.ts
- src/implementations/config/create.ts
- src/implementations/config/helpers.ts
qr code not appearing for other networks, such as maticmum
- `network` added in generated forms
- rename the networks to the correct names used on other tt applications
- remove conditional add `documentStorage`, field is now provided in tradetrust-config [reference config files](https://github.com/TradeTrust/tradetrust-config/blob/536d6f99a3783405540b32831c3dbcdcac0275a6/build/reference/config-v2.json#L7-L10) instead
https://www.pivotaltracker.com/story/show/183929424
> feat: config other networks

- src/commands/shared.ts
To revert `--encrypted-wallet-path` arg back to optional so that users can use `--key` or set their private key in their environment variable to be used 
- Removed `demandOption: true` from `withWalletOption()` option
> fix: make wallet path optional

- src/commands/shared.ts
- src/implementations/utils/wallet.ts
What is the background of this pull request?
My teams's access to aws also require a `SessionToken` to be included as part of the AWS credentials used.
- Add `session-token` option to `withAwsKmsSignerOption`
What are the related issues or stories?
> feat: add aws session-token option to withAwsKmsSignerOption

- README.md
- src/__tests__/verify.v2.e2e.test.ts
- src/__tests__/verify.v3.e2e.test.ts
- src/commands/config/config.type.ts
- src/commands/config/create.ts
- src/implementations/config/__tests__/config-reference-v3.json
- src/implementations/config/__tests__/create.test.ts
- src/implementations/config/__tests__/error-config-file.json
- src/implementations/config/__tests__/expected-config-file-output-v2.json
- src/implementations/config/__tests__/expected-config-file-output-v3.json
- src/implementations/config/__tests__/helpers.test.ts
- src/implementations/config/__tests__/input-config-file.json
- src/implementations/deploy/document-store/document-store.test.ts
- src/implementations/deploy/title-escrow-factory/title-escrow-factory.test.ts
- src/implementations/deploy/token-registry/token-registry.test.ts
- src/implementations/document-store/issue.test.ts
- src/implementations/document-store/revoke.test.ts
- src/implementations/document-store/transfer-ownership.test.ts
- src/implementations/title-escrow/acceptSurrendered.test.ts
- src/implementations/title-escrow/endorseNominatedBeneficiary.test.ts
- src/implementations/title-escrow/nominateBeneficiary.test.ts
- src/implementations/title-escrow/rejectSurrendered.test.ts
- src/implementations/title-escrow/surrenderDocument.test.ts
- src/implementations/title-escrow/transferHolder.test.ts
- src/implementations/title-escrow/transferOwners.test.ts
- src/implementations/token-registry/issue.test.ts
- src/implementations/transaction/transaction.test.ts
- src/implementations/utils/__tests__/wallet.test.ts
- src/implementations/wallet/create.ts
- src/utils.ts
Goerli Testnet has been deprecated. This PR is to update test cases to sepolia. 
*Note: The removal of Goerli Testnet for the commands should not be in this PR, we should be able to run cmd for goerli testnet until October 2023.*
- Update test files to use Sepolia.
- Update Config creation cmd to only use Testnets.
https://www.pivotaltracker.com/story/show/185533855
> fix: update goerli deprecation and change to sepolia

- .github/workflows/linters.yml
- README.md
To update a remote file in the documentation website which retrieve information from this readme, changes are proposed.
- Mainly editing the content.
> docs: edit oa-cli readme

- src/implementations/document-store/grant-role.ts
- src/implementations/document-store/issue.ts
- src/implementations/document-store/revoke-role.ts
- src/implementations/document-store/revoke.ts
- src/implementations/document-store/transfer-ownership.ts
- src/implementations/title-escrow/acceptSurrendered.ts
- src/implementations/title-escrow/endorseNominatedBeneficiary.ts
- src/implementations/title-escrow/nominateBeneficiary.ts
- src/implementations/title-escrow/rejectSurrendered.ts
- src/implementations/title-escrow/surrenderDocument.ts
- src/implementations/title-escrow/transferHolder.ts
- src/implementations/title-escrow/transferOwners.ts
- src/implementations/token-registry/issue.ts
Background:
[Original PR](https://github.com/Open-Attestation/open-attestation-cli/pull/193) to add callStatic.
Commands called on the Sepolia network fails when we try to invoke the callStatic methods with `gasFees`.
In this PR we remove that param from the callStatic invocations to still allow for the added validation but resolve such errors.
> feat: remove gasFees from callStatics

- package.json
With addition of `"performance-tests/**/*.ts"` in tsconfig.json, npm run build outputs 2 folders to `dist/cjs` instead of one.
This PR adds the `src` folder to allow the `pkg` command to locate index.js correctly.
> fix: add src to binary path

- README.md
- src/commands/config/config.type.ts
- src/commands/config/create.ts
- src/common/networks.ts
- https://polygon.technology/blog/introducing-the-amoy-testnet-for-polygon-pos
- https://www.alchemy.com/blog/polygon-mumbai-testnet-deprecation
- replace Polygon Mumbai with Polygon Amoy 
- https://docs.polygon.technology/pos/reference/rpc-endpoints/#mumbai-deprecating-soon
- https://polygon.technology/blog/introducing-the-amoy-testnet-for-polygon-pos (connect to Amoy)
> feat: migrate polygon mumbai to amoy
